"""TEST: columns renamed

Revision ID: 92872645c573
Revises: 7ea3cf9099f9
Create Date: 2022-07-14 14:11:27.956593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92872645c573'
down_revision = '7ea3cf9099f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stdin', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stdout', sa.Text(), nullable=True))
        batch_op.drop_column('test_output')
        batch_op.drop_column('test_input')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_input', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('test_output', sa.TEXT(), nullable=True))
        batch_op.drop_column('stdout')
        batch_op.drop_column('stdin')

    # ### end Alembic commands ###
