name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PEP8
        uses: quentinguidee/pep8-action@v1

      - name: Run Tests
        run: python -m unittest discover tests
        with:
          arguments: '--max-line-length=120 --ignore E122,E402 --exclude docs/*,migrations/*'